# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Button"
  description: ""
  icon: crop_7_5
  tags: 
    - buttons
    - Basic 

# Defines the structure of this component, as well as the default values
blueprint:
  link_url: ""
  call-to-action: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  link_url: '#'
  call-to-action: Call To Action
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
